# Configuration de Dependabot pour les mises à jour de version.
# Consultez la documentation pour toutes les options de configuration :
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Configuration pour l'écosystème npm
  - package-ecosystem: "npm" # Écosystème de package
    directory: "/" # Emplacement du fichier package.json
    schedule:
      interval: "weekly" # Fréquence des mises à jour (daily, weekly, monthly)

  # Configuration pour l'écosystème pip (Python)
  - package-ecosystem: "pip" # Écosystème de package
    directory: "/" # Emplacement du fichier requirements.txt
    schedule:
      interval: "weekly"

  # Configuration pour l'écosystème Maven (Java)
  - package-ecosystem: "maven" # Écosystème de package
    directory: "/" # Emplacement du fichier pom.xml
    schedule:
      interval: "weekly"

  # Configuration pour l'écosystème RubyGems (Ruby)
  - package-ecosystem: "rubygems" # Écosystème de package
    directory: "/" # Emplacement du fichier Gemfile
    schedule:
      interval: "weekly"
