name: SonarCloud and Lint Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  analysis:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=your_project_key
            -Dsonar.organization=your_organization_key
            -Dsonar.sources=.
            -Dsonar.tests=.
            -Dsonar.test.inclusions="**/*.spec.js,**/*.test.js"
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
          projectBaseDir: .

      - name: Run ESLint
        run: |
          npx eslint . --fix

      - name: Run Stylelint
        run: |
          npx stylelint "**/*.css" --fix

      - name: Commit and Push changes
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Auto-fix lint issues"
          git push origin ${{ github.head_ref }}
